LINUXDROID_PKG_HOMEPAGE=https://github.com/fribidi/fribidi/
LINUXDROID_PKG_DESCRIPTION="Implementation of the Unicode Bidirectional Algorithm"
LINUXDROID_PKG_VERSION=1.0.5
LINUXDROID_PKG_SHA256=6a64f2a687f5c4f203a46fa659f43dd43d1f8b845df8d723107e8a7e6158e4ce
LINUXDROID_PKG_SRCURL=https://github.com/fribidi/fribidi/releases/download/v$LINUXDROID_PKG_VERSION/fribidi-$LINUXDROID_PKG_VERSION.tar.bz2
LINUXDROID_PKG_DEPENDS="glib"
LINUXDROID_PKG_EXTRA_CONFIGURE_ARGS="--disable-docs"
