LINUXDROID_PKG_HOMEPAGE=https://dev.yorhel.nl/ncdu
LINUXDROID_PKG_DESCRIPTION="Disk usage analyzer"
LINUXDROID_PKG_VERSION=1.13
LINUXDROID_PKG_REVISION=1
LINUXDROID_PKG_SHA256=f4d9285c38292c2de05e444d0ba271cbfe1a705eee37c2b23ea7c448ab37255a
LINUXDROID_PKG_SRCURL=https://dev.yorhel.nl/download/ncdu-${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_DEPENDS="ncurses, libandroid-support"
LINUXDROID_PKG_EXTRA_CONFIGURE_ARGS="--with-shell=$LINUXDROID_PREFIX/bin/bash"
