MININIX_PKG_HOMEPAGE=https://newsboat.org/
MININIX_PKG_DESCRIPTION="RSS/Atom feed reader for the text console"
MININIX_PKG_API_LEVEL=24
MININIX_PKG_VERSION=2.13
MININIX_PKG_SHA256=c73613b4f08c875bae2c4e7828e67291e7599e9cabed528089f8378f520b335e
MININIX_PKG_SRCURL=https://newsboat.org/releases/${MININIX_PKG_VERSION}/newsboat-${MININIX_PKG_VERSION}.tar.xz
MININIX_PKG_DEPENDS="libandroid-support, libandroid-glob, json-c, libsqlite, libcurl, libxml2, stfl, ncurses, openssl"
MININIX_PKG_BUILD_IN_SRC=yes
MININIX_PKG_RM_AFTER_INSTALL="share/locale"
MININIX_PKG_CONFLICTS=newsbeuter
MININIX_PKG_REPLACES=newsbeuter
