LINUXDROID_PKG_HOMEPAGE=https://www.vanheusden.com/httping/
LINUXDROID_PKG_DESCRIPTION="ping-like program for http-requests"
LINUXDROID_PKG_VERSION=2.5
LINUXDROID_PKG_REVISION=2
LINUXDROID_PKG_SRCURL=https://fossies.org/linux/www/httping-${LINUXDROID_PKG_VERSION}.tgz
LINUXDROID_PKG_SHA256=3e895a0a6d7bd79de25a255a1376d4da88eb09c34efdd0476ab5a907e75bfaf8
LINUXDROID_PKG_BUILD_IN_SRC=yes
LINUXDROID_PKG_DEPENDS="fftw, libandroid-support, ncurses, openssl"
LINUXDROID_PKG_EXTRA_CONFIGURE_ARGS="--with-fftw3 --with-ncurses --with-openssl"
LINUXDROID_PKG_MAINTAINER="Pierre Rudloff @Rudloff"
