MININIX_PKG_HOMEPAGE=https://www.vanheusden.com/httping/
MININIX_PKG_DESCRIPTION="ping-like program for http-requests"
MININIX_PKG_VERSION=2.5
MININIX_PKG_REVISION=2
MININIX_PKG_SRCURL=https://fossies.org/linux/www/httping-${MININIX_PKG_VERSION}.tgz
MININIX_PKG_SHA256=3e895a0a6d7bd79de25a255a1376d4da88eb09c34efdd0476ab5a907e75bfaf8
MININIX_PKG_BUILD_IN_SRC=yes
MININIX_PKG_DEPENDS="fftw, libandroid-support, ncurses, openssl"
MININIX_PKG_EXTRA_CONFIGURE_ARGS="--with-fftw3 --with-ncurses --with-openssl"
MININIX_PKG_MAINTAINER="Pierre Rudloff @Rudloff"
