LINUXDROID_PKG_HOMEPAGE=https://cmake.org/
LINUXDROID_PKG_DESCRIPTION="Family of tools designed to build, test and package software"
LINUXDROID_PKG_VERSION=3.12.4
LINUXDROID_PKG_SHA256=5255584bfd043eb717562cff8942d472f1c0e4679c4941d84baadaa9b28e3194
LINUXDROID_PKG_SRCURL=https://www.cmake.org/files/v${LINUXDROID_PKG_VERSION:0:4}/cmake-${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_DEPENDS="libarchive, libcurl, libexpat, jsoncpp, libuv, rhash, make, clang"
LINUXDROID_PKG_FORCE_CMAKE=yes
LINUXDROID_PKG_EXTRA_CONFIGURE_ARGS="-DKWSYS_LFS_WORKS=ON -DBUILD_CursesDialog=ON"
