MININIX_SUBPKG_INCLUDE="$_jvm_dir/src.zip"
MININIX_SUBPKG_DEPENDS="openjdk-9-jre-headless"
MININIX_SUBPKG_DESCRIPTION="OpenJDK Development Kit (JDK) source files"
MININIX_SUBPKG_PLATFORM_INDEPENDENT=yes
