LINUXDROID_SUBPKG_INCLUDE="$_jvm_dir/src.zip"
LINUXDROID_SUBPKG_DEPENDS="openjdk-9-jre-headless"
LINUXDROID_SUBPKG_DESCRIPTION="OpenJDK Development Kit (JDK) source files"
LINUXDROID_SUBPKG_PLATFORM_INDEPENDENT=yes
