LINUXDROID_PKG_HOMEPAGE=https://lame.sourceforge.net/
LINUXDROID_PKG_DESCRIPTION="High quality MPEG Audio Layer III (MP3) encoder"
LINUXDROID_PKG_VERSION=3.100
LINUXDROID_PKG_SHA256=ddfe36cab873794038ae2c1210557ad34857a4b6bdc515785d1da9e175b1da1e
LINUXDROID_PKG_SRCURL=https://downloads.sourceforge.net/project/lame/lame/${LINUXDROID_PKG_VERSION}/lame-${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_EXTRA_CONFIGURE_ARGS="--disable-frontend"
LINUXDROID_PKG_RM_AFTER_INSTALL="share/man"
