LINUXDROID_PKG_HOMEPAGE=https://en.wikipedia.org/wiki/Mathomatic
LINUXDROID_PKG_DESCRIPTION="Simple CAS and symbolic calculator"
LINUXDROID_PKG_VERSION=16.0.5
LINUXDROID_PKG_REVISION=3
LINUXDROID_PKG_SRCURL="https://fossies.org/linux/misc/old/mathomatic-${LINUXDROID_PKG_VERSION}.tar.xz"
LINUXDROID_PKG_SHA256=7f525bdb2e13006549dd8f17906c26f926f5ac51174f02f074107c612491e05c
LINUXDROID_PKG_BUILD_IN_SRC=yes
LINUXDROID_PKG_EXTRA_MAKE_ARGS="READLINE=1"
LINUXDROID_PKG_DEPENDS="readline"
LINUXDROID_PKG_RM_AFTER_INSTALL="share/applications/mathomatic.desktop share/pixmaps"
LINUXDROID_PKG_MAINTAINER="Jonathan Badger @jhbadger"

linuxdroid_step_pre_configure() {
	rm $LINUXDROID_PKG_SRCDIR/CMakeLists.txt
	CPPFLAGS+=" -DUSE_TGAMMA -DBOLD_COLOR"
}
