LINUXDROID_PKG_HOMEPAGE=https://github.com/msgpack/msgpack-c/
LINUXDROID_PKG_DESCRIPTION="MessagePack implementation for C and C++"
LINUXDROID_PKG_VERSION=3.1.1
LINUXDROID_PKG_SHA256=8592d12e19ac3796889b8358bc8f78df9272e6aa7a9ea1834bafd68e4073549a
LINUXDROID_PKG_SRCURL=https://github.com/msgpack/msgpack-c/releases/download/cpp-${LINUXDROID_PKG_VERSION}/msgpack-${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_BUILD_IN_SRC=yes
LINUXDROID_PKG_EXTRA_CONFIGURE_ARGS="
-DMSGPACK_BUILD_EXAMPLES=OFF
-DMSGPACK_BUILD_TESTS=OFF
-DMSGPACK_ENABLE_CXX=OFF
"
