LINUXDROID_PKG_HOMEPAGE=https://rednex.github.io/rgbds/
LINUXDROID_PKG_DESCRIPTION="Rednex Game Boy Development System"
LINUXDROID_PKG_VERSION=0.3.7
LINUXDROID_PKG_SHA256=9ffdbdf223e40b18e0e64083356092d07c268b42b78d8fd29fcc468969936a04
LINUXDROID_PKG_SRCURL=https://github.com/rednex/rgbds/releases/download/v${LINUXDROID_PKG_VERSION}/rgbds-${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_DEPENDS="libpng"
LINUXDROID_PKG_BUILD_IN_SRC=true
LINUXDROID_PKG_EXTRA_MAKE_ARGS="PREFIX=${LINUXDROID_PREFIX} Q= STRIP="
