MININIX_PKG_HOMEPAGE=htts://github.com/tadfisher/pass-otp
MININIX_PKG_DESCRIPTION="A pass extension for managing one-time-password (OTP) tokens"
MININIX_PKG_MAINTAINER="Henrik Grimler @Grimler91"
MININIX_PKG_VERSION=1.1.1
MININIX_PKG_SHA256=edb3142ab81d70af4e6d1c7f13abebd7c349be474a3f9293d9648ee91b75b458
MININIX_PKG_SRCURL=https://github.com/tadfisher/pass-otp/archive/v${MININIX_PKG_VERSION}.tar.gz
MININIX_PKG_BUILD_IN_SRC=yes
MININIX_PKG_PLATFORM_INDEPENDENT=yes
MININIX_PKG_DEPENDS="pass, oathtool"
MININIX_PKG_SUGGESTS="libqrencode"
