LINUXDROID_PKG_HOMEPAGE=https://github.com/scop/bash-completion
LINUXDROID_PKG_DESCRIPTION="Programmable completion for the bash shell"
LINUXDROID_PKG_VERSION=2.8
LINUXDROID_PKG_SHA256=c01f5570f5698a0dda8dc9cfb2a83744daa1ec54758373a6e349bd903375f54d
LINUXDROID_PKG_SRCURL=https://github.com/scop/bash-completion/releases/download/${LINUXDROID_PKG_VERSION}/bash-completion-${LINUXDROID_PKG_VERSION}.tar.xz
LINUXDROID_PKG_DEPENDS="bash"
LINUXDROID_PKG_PLATFORM_INDEPENDENT=yes
