LINUXDROID_PKG_HOMEPAGE=https://gitlab.com/psmisc/psmisc
LINUXDROID_PKG_DESCRIPTION="Some small useful utilities that use the proc filesystem"
LINUXDROID_PKG_DEPENDS="ncurses"
LINUXDROID_PKG_VERSION=23.2
LINUXDROID_PKG_SHA256=4b7cbffdc9373474da49b85dc3457ae511c43dc7fa7d94513fe06f89dcb87880
LINUXDROID_PKG_SRCURL=https://fossies.org/linux/misc/psmisc-$LINUXDROID_PKG_VERSION.tar.xz
LINUXDROID_PKG_BUILD_IN_SRC=yes
LINUXDROID_PKG_RM_AFTER_INSTALL="bin/pstree.x11"
