MININIX_PKG_HOMEPAGE=https://lldb.llvm.org
MININIX_PKG_DESCRIPTION="LLVM based debugger"
MININIX_PKG_VERSION=7.0.0
MININIX_PKG_SHA256=7ff6d8fee49977d25b3b69be7d22937b92592c7609cf283ed0dcf9e5cd80aa32
MININIX_PKG_SRCURL=https://releases.llvm.org/${MININIX_PKG_VERSION}/lldb-$MININIX_PKG_VERSION.src.tar.xz
MININIX_PKG_DEPENDS="libedit, libllvm, libxml2, ncurses-ui-libs"
MININIX_PKG_BLACKLISTED_ARCHES="i686"
MININIX_PKG_HAS_DEBUG=no
MININIX_PKG_EXTRA_CONFIGURE_ARGS="
-DLLDB_DISABLE_CURSES=0
-DLLDB_DISABLE_LIBEDIT=0
-DLLDB_DISABLE_PYTHON=1
-DLLVM_CONFIG=$MININIX_PREFIX/bin/llvm-config
-DLLVM_ENABLE_TERMINFO=1
-DLLVM_LINK_LLVM_DYLIB=ON
"

mininix_step_pre_configure() {
	LDFLAGS+=" -Wl,--exclude-libs=libLLVMSupport.a"
}

mininix_step_post_make_install() {
	cp $MININIX_PKG_SRCDIR/docs/lldb.1 $MININIX_PREFIX/share/man/man1
}
