LINUXDROID_PKG_HOMEPAGE=https://github.com/esnet/iperf
LINUXDROID_PKG_DESCRIPTION="TCP, UDP, and SCTP network bandwidth measurement tool"
LINUXDROID_PKG_VERSION=3.6
LINUXDROID_PKG_REVISION=1
LINUXDROID_PKG_SHA256=de5d51e46dc460cc590fb4d44f95e7cad54b74fea1eba7d6ebd6f8887d75946e
LINUXDROID_PKG_SRCURL=https://fossies.org/linux/privat/iperf-$LINUXDROID_PKG_VERSION.tar.gz
LINUXDROID_PKG_DEPENDS="openssl"
