LINUXDROID_PKG_HOMEPAGE=http://bvi.sourceforge.net/
LINUXDROID_PKG_DESCRIPTION="Binary file editor based on vi"
LINUXDROID_PKG_DEPENDS="ncurses"
LINUXDROID_PKG_VERSION=1.4.0
LINUXDROID_PKG_REVISION=1
LINUXDROID_PKG_SRCURL=http://sourceforge.net/projects/bvi/files/bvi/${LINUXDROID_PKG_VERSION}/bvi-${LINUXDROID_PKG_VERSION}.src.tar.gz
LINUXDROID_PKG_SHA256=015a3c2832c7c097d98a5527deef882119546287ba8f2a70c736227d764ef802
LINUXDROID_PKG_BUILD_IN_SRC="yes"
LINUXDROID_PKG_EXTRA_CONFIGURE_ARGS="ac_cv_lib_ncursesw6_addnwstr=yes"
LINUXDROID_PKG_RM_AFTER_INSTALL="share/applications share/pixmaps"
