MININIX_PKG_HOMEPAGE=http://bvi.sourceforge.net/
MININIX_PKG_DESCRIPTION="Binary file editor based on vi"
MININIX_PKG_DEPENDS="ncurses"
MININIX_PKG_VERSION=1.4.0
MININIX_PKG_REVISION=1
MININIX_PKG_SRCURL=http://sourceforge.net/projects/bvi/files/bvi/${MININIX_PKG_VERSION}/bvi-${MININIX_PKG_VERSION}.src.tar.gz
MININIX_PKG_SHA256=015a3c2832c7c097d98a5527deef882119546287ba8f2a70c736227d764ef802
MININIX_PKG_BUILD_IN_SRC="yes"
MININIX_PKG_EXTRA_CONFIGURE_ARGS="ac_cv_lib_ncursesw6_addnwstr=yes"
MININIX_PKG_RM_AFTER_INSTALL="share/applications share/pixmaps"
