LINUXDROID_PKG_HOMEPAGE=http://joe-editor.sourceforge.net
LINUXDROID_PKG_DESCRIPTION="Wordstar like text editor"
LINUXDROID_PKG_DEPENDS="ncurses, libutil"
LINUXDROID_PKG_CONFLICTS="jupp"
LINUXDROID_PKG_VERSION=4.6
LINUXDROID_PKG_SHA256=495a0a61f26404070fe8a719d80406dc7f337623788e445b92a9f6de512ab9de
LINUXDROID_PKG_SRCURL=https://sourceforge.net/projects/joe-editor/files/JOE%20sources/joe-${LINUXDROID_PKG_VERSION}/joe-${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_EXTRA_CONFIGURE_ARGS="--disable-termcap"
