MININIX_SUBPKG_INCLUDE="include lib/pkgconfig"
MININIX_SUBPKG_DESCRIPTION="Development files for texlive"
MININIX_SUBPKG_DEPENDS="texlive-bin"
MININIX_SUBPKG_REPLACES="texlive-dev"
MININIX_SUBPKG_CONFLICTS="texlive-dev"
