LINUXDROID_PKG_HOMEPAGE=https://luarocks.org/
LINUXDROID_PKG_DESCRIPTION="Deployment and management system for Lua modules"
LINUXDROID_PKG_VERSION=2.4.4
LINUXDROID_PKG_REVISION=1
LINUXDROID_PKG_SHA256=3938df33de33752ff2c526e604410af3dceb4b7ff06a770bc4a240de80a1f934
LINUXDROID_PKG_SRCURL=https://luarocks.org/releases/luarocks-${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_DEPENDS="curl, lua"
LINUXDROID_PKG_BUILD_DEPENDS="liblua-dev"
LINUXDROID_PKG_BUILD_IN_SRC=yes
LINUXDROID_PKG_PLATFORM_INDEPENDENT=yes

linuxdroid_step_configure () {
	./configure --prefix=$LINUXDROID_PREFIX \
		--with-lua=$LINUXDROID_PREFIX \
		--lua-version=5.3
}
