LINUXDROID_PKG_HOMEPAGE=https://github.com/dylanaraps/neofetch
LINUXDROID_PKG_DESCRIPTION="Simple system information script"
LINUXDROID_PKG_MAINTAINER="Muhammad Herdiansyah @konimex"
LINUXDROID_PKG_VERSION=5.0.0
LINUXDROID_PKG_SHA256=2a4f4853bf83b88a037994dbc53a90c8bd5708f5eeb3392f56d4e49c49d995b3
LINUXDROID_PKG_SRCURL=https://github.com/dylanaraps/neofetch/archive/${LINUXDROID_PKG_VERSION}/neofetch-${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_DEPENDS="bash"
LINUXDROID_PKG_EXTRA_MAKE_ARGS="PREFIX=$LINUXDROID_PREFIX SYSCONFDIR=$LINUXDROID_PREFIX/etc"
LINUXDROID_PKG_BUILD_IN_SRC=yes
LINUXDROID_PKG_PLATFORM_INDEPENDENT=yes
