MININIX_PKG_HOMEPAGE=https://github.com/dylanaraps/neofetch
MININIX_PKG_DESCRIPTION="Simple system information script"
MININIX_PKG_MAINTAINER="Muhammad Herdiansyah @konimex"
MININIX_PKG_VERSION=5.0.0
MININIX_PKG_SHA256=2a4f4853bf83b88a037994dbc53a90c8bd5708f5eeb3392f56d4e49c49d995b3
MININIX_PKG_SRCURL=https://github.com/dylanaraps/neofetch/archive/${MININIX_PKG_VERSION}/neofetch-${MININIX_PKG_VERSION}.tar.gz
MININIX_PKG_DEPENDS="bash"
MININIX_PKG_EXTRA_MAKE_ARGS="PREFIX=$MININIX_PREFIX SYSCONFDIR=$MININIX_PREFIX/etc"
MININIX_PKG_BUILD_IN_SRC=yes
MININIX_PKG_PLATFORM_INDEPENDENT=yes
