LINUXDROID_PKG_HOMEPAGE=https://tls.mbed.org/
LINUXDROID_PKG_DESCRIPTION="Light-weight cryptographic and SSL/TLS library"
LINUXDROID_PKG_MAINTAINER="Andy Li @andyli"
LINUXDROID_PKG_VERSION=2.13.1
LINUXDROID_PKG_SHA256=e62fdea0110d3aa9082b3e1ccdbbaf520161830b1f3a57ae3124a7d5963c2a37
LINUXDROID_PKG_SRCURL=https://github.com/ARMmbed/mbedtls/archive/mbedtls-$LINUXDROID_PKG_VERSION.tar.gz
LINUXDROID_PKG_EXTRA_CONFIGURE_ARGS="
-DUSE_STATIC_MBEDTLS_LIBRARY=OFF
-DUSE_SHARED_MBEDTLS_LIBRARY=ON
-DENABLE_TESTING=OFF
-DENABLE_PROGRAMS=OFF
"
