MININIX_PKG_HOMEPAGE=https://tls.mbed.org/
MININIX_PKG_DESCRIPTION="Light-weight cryptographic and SSL/TLS library"
MININIX_PKG_MAINTAINER="Andy Li @andyli"
MININIX_PKG_VERSION=2.14.0
MININIX_PKG_SHA256=3e733731eca47ffdc85330cde47774e075f5d1326e413555713dec8bf9c31eb3
MININIX_PKG_SRCURL=https://github.com/ARMmbed/mbedtls/archive/mbedtls-$MININIX_PKG_VERSION.tar.gz
MININIX_PKG_EXTRA_CONFIGURE_ARGS="
-DUSE_STATIC_MBEDTLS_LIBRARY=OFF
-DUSE_SHARED_MBEDTLS_LIBRARY=ON
-DENABLE_TESTING=OFF
-DENABLE_PROGRAMS=OFF
"
