LINUXDROID_PKG_HOMEPAGE=https://github.com/martanne/dvtm
LINUXDROID_PKG_DESCRIPTION="Terminal tiling window manager"
LINUXDROID_PKG_VERSION=0.15
LINUXDROID_PKG_REVISION=1
LINUXDROID_PKG_SRCURL=https://github.com/martanne/dvtm/archive/v${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_SHA256=496eada13d8abaa8d772279746f78b0c6fed11b560599490f3e70ebc21197bf0
LINUXDROID_PKG_BUILD_IN_SRC=yes
LINUXDROID_PKG_DEPENDS="libutil, ncurses"

linuxdroid_step_pre_configure() {
	CFLAGS+=" $CPPFLAGS"
}
