LINUXDROID_PKG_HOMEPAGE=http://caca.zoy.org/wiki/toilet
LINUXDROID_PKG_DESCRIPTION="FIGlet-compatible display of large colourful characters in text mode"
LINUXDROID_PKG_VERSION=0.3
LINUXDROID_PKG_REVISION=1
LINUXDROID_PKG_SRCURL=http://fossies.org/linux/privat/toilet-${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_SHA256=89d4b530c394313cc3f3a4e07a7394fa82a6091f44df44dfcd0ebcb3300a81de
LINUXDROID_PKG_DEPENDS="libcaca"
LINUXDROID_PKG_BUILD_IN_SRC=yes
