LINUXDROID_PKG_HOMEPAGE=http://xmlstar.sourceforge.net/
LINUXDROID_PKG_DESCRIPTION="Command line XML toolkit"
LINUXDROID_PKG_VERSION=1.6.1
LINUXDROID_PKG_REVISION=2
LINUXDROID_PKG_SRCURL=http://downloads.sourceforge.net/project/xmlstar/xmlstarlet/${LINUXDROID_PKG_VERSION}/xmlstarlet-${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_SHA256=15d838c4f3375332fd95554619179b69e4ec91418a3a5296e7c631b7ed19e7ca
LINUXDROID_PKG_DEPENDS="libxslt"
LINUXDROID_PKG_EXTRA_CONFIGURE_ARGS="--with-libxml-include-prefix=${LINUXDROID_PREFIX}/include/libxml2"
LINUXDROID_PKG_BUILD_IN_SRC=yes
