LINUXDROID_PKG_HOMEPAGE=https://otr.cypherpunks.ca
LINUXDROID_PKG_DESCRIPTION="Off-the-Record (OTR) Messaging allows you to have private conversations over instant messaging by providing: Encryption, Authentication, Deniability, Perfect forward secrecy"
LINUXDROID_PKG_VERSION=4.1.1
LINUXDROID_PKG_MAINTAINER="Oliver Schmidhauser @Neo-Oli"
LINUXDROID_PKG_SRCURL=https://otr.cypherpunks.ca/libotr-${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_SHA256=8b3b182424251067a952fb4e6c7b95a21e644fbb27fbd5f8af2b2ed87ca419f5
LINUXDROID_PKG_DEPENDS="libgcrypt"
LINUXDROID_PKG_BUILD_DEPENDS="libgpg-error"
LINUXDROID_PKG_BUILD_IN_SRC=yes
