MININIX_PKG_HOMEPAGE=https://otr.cypherpunks.ca
MININIX_PKG_DESCRIPTION="Off-the-Record (OTR) Messaging allows you to have private conversations over instant messaging by providing: Encryption, Authentication, Deniability, Perfect forward secrecy"
MININIX_PKG_VERSION=4.1.1
MININIX_PKG_MAINTAINER="Oliver Schmidhauser @Neo-Oli"
MININIX_PKG_SRCURL=https://otr.cypherpunks.ca/libotr-${MININIX_PKG_VERSION}.tar.gz
MININIX_PKG_SHA256=8b3b182424251067a952fb4e6c7b95a21e644fbb27fbd5f8af2b2ed87ca419f5
MININIX_PKG_DEPENDS="libgcrypt"
MININIX_PKG_BUILD_DEPENDS="libgpg-error"
MININIX_PKG_BUILD_IN_SRC=yes
