LINUXDROID_PKG_HOMEPAGE=https://github.com/westes/flex
LINUXDROID_PKG_DESCRIPTION="Fast lexical analyser generator"
LINUXDROID_PKG_VERSION=2.6.4
LINUXDROID_PKG_SRCURL=https://github.com/westes/flex/releases/download/v${LINUXDROID_PKG_VERSION}/flex-${LINUXDROID_PKG_VERSION}.tar.gz
LINUXDROID_PKG_SHA256=e87aae032bf07c26f85ac0ed3250998c37621d95f8bd748b31f15b33c45ee995
LINUXDROID_PKG_DEPENDS="m4"
LINUXDROID_PKG_HOSTBUILD=true
LINUXDROID_PKG_EXTRA_CONFIGURE_ARGS+="ac_cv_path_M4=$LINUXDROID_PREFIX/bin/m4"
LINUXDROID_PKG_NO_DEVELSPLIT=yes
LINUXDROID_PKG_CONFLICTS="flex-dev"
LINUXDROID_PKG_REPLACES="flex-dev"

# Work around https://github.com/westes/flex/issues/241 when building
# under ubuntu 17.10:
LINUXDROID_PKG_EXTRA_HOSTBUILD_CONFIGURE_ARGS="CFLAGS=-D_GNU_SOURCE=1"

linuxdroid_step_pre_configure() {
	mkdir -p $LINUXDROID_PKG_BUILDDIR/src/
	cp $LINUXDROID_PKG_HOSTBUILD_DIR/src/stage1flex $LINUXDROID_PKG_BUILDDIR/src/stage1flex
	touch -d "next hour" $LINUXDROID_PKG_BUILDDIR/src/stage1flex
}
